apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Values.namespace }}
  name: ananse-injector-config
data:
  SIDECAR_IMAGE: "{{ .Values.sidecar.image }}"
  INIT_IMAGE: "{{ .Values.init.image }}"
  PROXY_PORT: "15001"
  INBOUND_PORT: "15006"
  PROXY_UID: "1337"
  PROXY_MODE: "{{ .Values.proxy.mode }}"
  CONTROL_PLANE_ENDPOINT: "ananse-controlplane.{{ .Values.namespace }}.svc:50051"
  METRICS_PORT: "{{ .Values.metrics.port }}"
  DEBUG_MODE: "{{ .Values.debug_mode }}"
