{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ananse
  namespace: {{ .Values.namespace }}
  labels:
    app: ananse
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: webhook-ananse
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
{{- end }}
