apiVersion: v1
kind: Service
metadata:
  name: ananse-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: webhook-ananse
spec:
  selector:
    app: webhook-ananse
  ports:
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: 8443
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}