apiVersion: v1
kind: Service
metadata:
    name: ananse-controlplane
    namespace: ananse-system
spec:
    selector:
      app: webhook-ananse
    ports:
      - port: 50051
        targetPort: 50051