apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-gateway
  namespace: ananse
  labels:
    app: proxy-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-gateway
  template:
    metadata:
      labels:
        app: proxy-gateway
    spec:
      serviceAccountName: ananse-controlplane
      containers:
      - name: proxy-debug
        image: anthony4m/ananse-proxy:debug-v1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["while true; do /usr/local/bin/dlv exec /server --headless --listen=:2345 --api-version=2 --accept-multiclient --continue || true; sleep 2; done"]
        ports:
        - containerPort: 2345
        - containerPort: 8089
        - containerPort: 9090
        env:
          - name: ANANSE_MODE
            value: "sidecar"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "otel-collector.monitoring.svc.cluster.local:4317"
      - name: controlplane
        image: controlplane:latest
        imagePullPolicy: IfNotPresent
        args: ["--k8s"]
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: config-volume
          mountPath: /root/config
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: ananse-config
      - name: webhook-certs
        secret:
          secretName: ananse-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ananse
spec:
  selector:
    app: proxy-gateway
  ports:
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
    - name: http
      port: 8089
      targetPort: 8089
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer
