apiVersion: v1
kind: Service
metadata:
  name: ananse-webhook
  namespace: ananse-system
  labels:
    app: webhook-ananse
spec:
  selector:
    app: webhook-ananse
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443