proxy:
  port: 8089
  metrics_port: 9090
  health_check_interval: 3

services:
  - name: analytics-upstream
    endpoints:
      - address: "localhost:5004"
      - address: "localhost:5003"
      - address: "localhost:5002"
      - address: "localhost:5001"
    routes:
      - path: "/analytics"
        methods: ["GET", "POST"]