proxy:
  port: 8089
  metrics_port: 9090
  health_check_interval: 30

services:
  - name: analytics-services
    endpoints:
      - address: "localhost:5004"
    routes:
      - path: "/analytics"
        methods: ["GET", "POST"]
  - name: auth-service
    endpoints:
        - address: "localhost:5001"
    routes:
        - path: "/auth"
          methods: ["GET", "POST"]
  - name: payments-service
    endpoints:
      - address: "localhost:5003"
    routes:
        - path: "/payments"
          methods: ["GET","POST"]
  - name: users-service
    endpoints:
        - address: "localhost:5002"
    routes:
      - path: "/users"
        methods: ["GET","POST"]


